### ISSUE TITLE
Merchants get killed when traveling to new city over local network

### ISSUE THREAD

**Issue by HannanSolo** [JasonFantl/Simulated-Economy-Tutorial#1]
In  Winterhold to Riverside merchants who travel to Riverside disappear from the merchant pool

**Comment by JasonFantl** [comment]
The Faraway collation would like to assure all, the issue has been swiftly and thoroughly dealt with. A group of marauding internet trolls were identified and dispatched with. The travelWays always have been, and always be, the safest mode of transport for merchants, and will continue to be so with your generous support provided through the travelWays tax.

**Comment by HannanSolo** [comment]
Glad to hear these capitalist merchants are not taking our kingdom's wealth all for themselves.
